site_name: Home Assistant
site_description: 'Home Assistant Configuration'
site_author: 'Venkat Venkataramanan'
copyright: 2020 venkat.ca
site_url: https://torvenkat.github.io/hadoc
docs_dir: docs/
repo_name: 'torvenkat/hadocs'
repo_url: 'https://github.com/torvenkat/hadocs'
theme: 
  name: material
  custom_dir: 'theme'
  logo: images/logo.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
  palette:
    primary: 'green'
    accent: 'light green'
  font:
    text: Roboto
    code: Fira Code  
extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
plugins:
    - search:
        lang: 'en'
    - awesome-pages
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true              