site_name: Home Assistant
site_description: 'Home Assistant Configuration'
site_author: 'Venkat Venkataramanan'
docs_dir: docs/
repo_name: 'torvenkat/hadocs'
repo_url: 'https://github.com/torvenkat/hadocs'
nav:
    - Home: index.md
    - About: about.md
theme: 
  name: material
  custom_dir: 'theme'
  logo: images/logo.svg
  features:
    - tabs
  palette:
    primary: 'green'
    accent: 'light green'
  font:
    text: Roboto
    code: Fira Code  